#!/bin/sh
set -e

mkdir -p /tmp/tailscale

# Start tailscaled in background
/var/runtime/tailscaled --tun=userspace-networking --socks5-server=localhost:1055 &
sleep 2  # give it a moment to start

# Bring up Tailscale once
/var/runtime/tailscale up --authkey="$TAILSCALE_AUTHKEY" --hostname=aws-lambda-app

echo "Tailscale started"

# Start Lambda runtime
if [ -z "${AWS_LAMBDA_RUNTIME_API}" ]; then
  exec env ALL_PROXY="socks5://localhost:1055/" /usr/local/bin/aws-lambda-rie /var/lang/bin/python3.6 -m awslambdaric "$@"
else
  exec env ALL_PROXY="socks5://localhost:1055/" /var/lang/bin/python3.6 -m awslambdaric "$@"
fi
